#!/bin/bash
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --mem=256G
#SBATCH -p qTRDHM
#SBATCH --time=20:00:00
#SBATCH -J GICAfbirn
#SBATCH -e /data/users2/jwardell1/ica-torch-gica/standalone_gica_script/group_level_analysis/jobs/error%A.err
#SBATCH -o /data/users2/jwardell1/ica-torch-gica/standalone_gica_script/group_level_analysis/jobs/out%A.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

sleep 5s


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

conda activate /data/users2/jwardell1/miniconda3/envs/ica-torch


GICA_DIR=/data/users2/jwardell1/ica-torch-gica/standalone_gica_script

#PATHS_FILE=${GICA_DIR}/input_data/sub_level_pca_files.txt
PATHS_FILE=${GICA_DIR}/input_data/sub_level_pca_files.dbg

MASK_FILE=/data/users2/jwardell1/nshor_docker/examples/fbirn-project/FBIRN/group_mean_masks/groupmeanmask_3mm.nii

OUTPUT_DIR=${GICA_DIR}/output_data

python ${GICA_DIR}/gica_script.py $PATHS_FILE $MASK_FILE $OUTPUT_DIR

#python ${GICA_DIR}/plot_comps.py


wait

sleep 10s
